In [83]:
%store -r df_classes
df_classes[0].shape

(76, 6)

## Train HMM

https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.226.3759&rep=rep1&type=pdf

https://learning.oreilly.com/library/view/python-machine-learning/9781786464477/ch07s08.html#ch07lvl2sec94

### Calculate Gaussian Mixture of model to find observation probability

In [81]:
from hmmlearn import hmm
import numpy as np
import pickle

In [3]:
from sklearn.mixture import GaussianMixture

# X0 = df_classes[0][['angles', 'x', 'y']]

# GMM = GaussianMixture(n_components=3, random_state=0).fit(X0) BUGGATO

In [78]:


# from baum_welch import baum_welch

# data = df_classes[0][['angles']].values
# data_list_append = data.tolist()
# data_list_append = [ three for one in data_list_append for two in one for three in two] 

# # TRY ONLY WI CURVATURE (ANGLE)
# # 6 states
# initial_prob = np.array([1, 0, 0, 0, 0, 0])
# transition_prob = np.ones((6, 6))
# transition_prob = transition_prob / np.sum(transition_prob, axis=1)
# emission_prob = np.ones((6, 1)) # I don't know how many
# emission_prob = emission_prob / np.sum(emission_prob, axis=1).reshape(-1, 1)

# n_iter = 20
# # To go, data has to be a list of numbers

# transition_true, emission_true = baum_welch(data_list_append, initial_prob, transition_prob, emission_prob, n_iter)

# print("new transition_prob: ", transition_true, "\nnew emission_prob: ", emission_true)


In [73]:
# https://hmmlearn.readthedocs.io/en/latest/tutorial.html#working-with-multiple-sequences

#           Delete this cell

data_true = df_classes[0][['angles']].values.tolist()
data_list_try = np.array([ [three] for one in data_true for two in one for three in two])
len_list_try = [len(two) for one in data_true for two in one ]


print(type(data_list_try[0]))
print(data_list_try.shape)
print(type(len_list_try))

hmm.GaussianHMM(n_components=6).fit(data_list_try, len_list_try)

<class 'numpy.ndarray'>
(3905, 1)
<class 'list'>


GaussianHMM(n_components=6)

In [91]:
n_iter=100
# compore to hmmlearn
# model = hmm.MultinomialHMM(n_components=6, n_iter=n_iter, init_params="", params="te", tol=0, verbose=True)
model = hmm.GaussianHMM(n_components=6, n_iter=n_iter, verbose=True, algorithm="viterbi")

data_true = df_classes[0][['angles']].values.tolist()
data_list = np.array([ [three] for one in data_true for two in one for three in two])
len_list = [len(two) for one in data_true for two in one ]

initial_prob = np.array([1, 0, 0, 0, 0, 0])
transition_prob = np.ones((6, 6))
transition_prob = transition_prob / np.sum(transition_prob, axis=1)
emission_prob = np.ones((6, 1)) # I don't know how many
emission_prob = emission_prob / np.sum(emission_prob, axis=1)

model.startprob_ = initial_prob
model.transmat_ = transition_prob
model.emissionprob_ = emission_prob

model.fit(data_list, len_list)
# model.fit(data_list_try)
print("initial probability: ", model.startprob_)
print(f'transition: \n{model.transmat_}')
print(f'emission: \n{model.emissionprob_}')

with open ('models/hmm_model_0.pkl', 'wb') as f: #Save model
    pickle.dump(model, f)

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'
         1       -8468.4270             +nan
         2       -7380.1263       +1088.3006
         3       -6290.4570       +1089.6693
         4       -5801.7235        +488.7335
         5       -5555.1579        +246.5656
         6       -5064.0650        +491.0928
         7       -4348.7377        +715.3273
         8       -3604.6437        +744.0940
         9       -2898.7447        +705.8991
        10       -2510.2425        +388.5022
        11       -2442.1561         +68.0864
        12       -2426.3595         +15.7966
        13       -2416.4979          +9.8616
        14       -2409.4290          +7.0689
        15       -2404.3855          +5.0435
        16       -2400.9280          +3.4575
        17       -2398.5458

initial probability:  [0.05012094 0.1316314  0.01673264 0.38121848 0.05193652 0.36836003]
transition: 
[[8.81371805e-001 2.30877959e-014 1.39475357e-003 1.08628360e-001
  5.82877140e-003 2.77631002e-003]
 [2.68316228e-003 8.91447569e-001 1.00091432e-001 7.63690521e-190
  1.99340251e-110 5.77783660e-003]
 [9.11569919e-138 8.21097128e-003 8.74974496e-001 3.00295096e-292
  1.16814532e-001 6.64902135e-191]
 [8.26016107e-003 1.69484214e-003 8.81714647e-105 8.41669877e-001
  1.67968534e-038 1.48375120e-001]
 [1.22006921e-001 5.76418643e-045 4.77335670e-003 1.76722897e-092
  8.73219722e-001 4.17818178e-180]
 [5.06607984e-003 1.09138750e-001 1.65462857e-003 4.22872060e-002
  1.38267706e-051 8.41853335e-001]]
emission: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


        53       -2385.1909          +0.0106
        54       -2385.1813          +0.0096
