In [3]:
import pickle
import numpy as np
import pandas as pd
from sklearn.metrics.cluster import contingency_matrix 

In [4]:
%store -r test

# Take the name of the different classes (e.g. '0', '1', '2', ...)
classes = test.groupby(['label'])['label'].unique().index.to_list()

In [6]:
predicted_test = test.copy()

feature_1= 'x'
feature_2='y'
feature_3='arctan_1'

models = []
for n_class in classes: # Can be thrown an expection beacuse this is the labels of the test set and not of the models (train set)
    model = pickle.load(open('models_7/'+str(n_class)+'hmm_model.pkl', 'rb'))
    models.append(model)

#log_likelihoods = pd.DataFrame()
#log_likelihoods['predicted_class'] = classes
#log_like_max = []
#top_3_loglikelihood = []
top_3_predicted_classes = []
predicted_class = []
#is_predicted = []
true_label=[]

for i in range(len(test)):
    angle_1 = test[feature_1].iloc[i]
    angle_2 = test[feature_2].iloc[i]
    angle_3 = test[feature_3].iloc[i]
 
    X=np.array([angle_1,angle_2,angle_3]).T
    print(X)
    true_label.append(test['label'].iloc[i])
    list_log_likelihoods = []
    for model in models:
        
        list_log_likelihoods.append(model.score(X,lengths=len(X)))
        pass

    predicted_class.append(np.argmax(list_log_likelihoods))

    top_3_values = sorted(list_log_likelihoods)[-3:]
    top_3_predicted_classes.append([i for i, x in enumerate(list_log_likelihoods) if x == top_3_values[0] or x == top_3_values[1] or x == top_3_values[2]])
    

[[6.75e+02 1.27e+02 1.90e-01]
 [6.70e+02 1.21e+02 1.80e-01]
 [6.70e+02 1.18e+02 1.70e-01]
 [6.70e+02 1.14e+02 1.70e-01]
 [6.70e+02 1.13e+02 1.70e-01]
 [6.70e+02 1.16e+02 1.70e-01]
 [6.67e+02 1.26e+02 1.90e-01]
 [6.67e+02 1.38e+02 2.00e-01]
 [6.68e+02 1.62e+02 2.40e-01]
 [6.69e+02 1.71e+02 2.50e-01]
 [6.70e+02 2.05e+02 3.00e-01]
 [6.70e+02 2.31e+02 3.30e-01]
 [6.70e+02 2.59e+02 3.70e-01]
 [6.70e+02 3.05e+02 4.30e-01]
 [6.70e+02 3.36e+02 4.60e-01]
 [6.71e+02 3.69e+02 5.00e-01]
 [6.73e+02 4.03e+02 5.40e-01]
 [6.74e+02 4.52e+02 5.90e-01]
 [6.74e+02 4.84e+02 6.20e-01]
 [6.73e+02 5.14e+02 6.50e-01]
 [6.73e+02 5.56e+02 6.90e-01]
 [6.73e+02 5.80e+02 7.10e-01]
 [6.74e+02 6.02e+02 7.30e-01]
 [6.74e+02 6.27e+02 7.50e-01]
 [6.75e+02 6.38e+02 7.60e-01]
 [6.75e+02 6.46e+02 7.60e-01]
 [6.75e+02 6.53e+02 7.70e-01]
 [6.75e+02 6.56e+02 7.70e-01]
 [6.75e+02 6.57e+02 7.70e-01]]
[[5.33e+02 2.34e+02 4.10e-01]
 [5.92e+02 2.22e+02 3.60e-01]
 [6.88e+02 2.21e+02 3.10e-01]
 [7.59e+02 2.29e+02 2.90e-01]
 [8.22e+0

In [38]:
print(predicted_class)
print(true_label)

print(len(predicted_class))
print(len(true_label))

[3, 3, 3, 5, 3, 8, 3, 2, 5, 8, 5, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 8, 3, 3, 2, 5, 3, 5, 3, 8, 5, 3, 3, 3, 5, 3, 3, 1, 3, 3, 3, 5, 3, 3, 5, 8, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 8, 8, 8, 3, 3, 3, 3, 2, 3, 2, 2, 3, 3, 8, 8, 3, 3, 5, 3, 3, 3, 3, 2, 3, 3, 3, 1, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 8, 2, 5, 5, 3, 3, 5, 5, 8, 3, 3, 2, 3, 8, 3, 2, 5, 3, 3, 3, 2, 2, 5, 3, 3, 8, 3, 3, 8, 2, 8, 3, 8, 8, 8, 2, 2, 3, 5, 8, 3, 3, 3, 3, 3, 8, 5, 3, 3, 3, 3, 5, 3, 3, 3, 1, 3, 1, 2, 3, 3, 3, 8, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 8, 3, 8, 3]
[1, 8, 2, 6, 6, 5, 1, 8, 6, 9, 8, 1, 2, 2, 0, 9, 0, 3, 9, 1, 5, 7, 6, 0, 8, 5, 3, 7, 3, 9, 3, 6, 3, 8, 3, 8, 8, 9, 0, 1, 6, 8, 6, 6, 5, 7, 3, 2, 8, 3, 2, 3, 8, 2, 2, 2, 6, 7, 7, 9, 5, 6, 8, 6, 3, 6, 7, 7, 0, 3, 9, 0, 0, 2, 0, 2, 3, 1, 1, 5, 3, 6, 0, 8, 8, 7, 9, 2, 9, 5, 9, 8, 1, 2, 0, 6, 7, 7, 9, 8, 7, 8, 8, 0, 9, 0, 3, 0, 2, 9, 6, 3, 6, 2, 5, 2, 7, 0, 9, 2, 3, 9, 6, 1, 7, 0, 7, 1, 9, 7, 7, 9, 9, 0, 5, 7, 3, 2, 3, 2, 2, 9, 6, 2, 6, 2, 0, 2, 1, 2, 3, 9, 0, 7, 9, 0, 0, 0,

In [39]:
matrix=contingency_matrix(true_label, predicted_class)
print(matrix)

[[ 0  4 14  2  1]
 [ 0  0 12  0  0]
 [ 0  0 24  2  0]
 [ 0  2 19  2  0]
 [ 0  1  4  3  1]
 [ 0  1 17  4  0]
 [ 1  5  1  1 11]
 [ 1  4 10  4  0]
 [ 2  7  2  2 11]]


In [40]:

accuracy=np.sum(np.diag(matrix))/np.sum(matrix)
print("Accuracy: ", accuracy)

Accuracy:  0.15428571428571428


In [ ]:
# Calculate top 3 accuracy
sum_top_3 = 0
for i in range(len(top_3_predicted_classes)):
    if true_label[i] in top_3_predicted_classes[i]:
        sum_top_3 += 1

accuracy_top_3 = sum_top_3/len(predicted_test["label"])
print("Accuracy top 3: ", accuracy_top_3)