In [35]:
import pickle
import numpy as np
import pandas as pd
from sklearn.metrics.cluster import contingency_matrix 

In [36]:
%store -r test

# Take the name of the different classes (e.g. '0', '1', '2', ...)
classes = test.groupby(['label'])['label'].unique().index.to_list()

In [37]:
predicted_test = test.copy()

feature_1= 'x'
feature_2='y'
feature_3='arctan_1'

models = []
for n_class in classes: # Can be thrown an expection beacuse this is the labels of the test set and not of the models (train set)
    model = pickle.load(open('models_7/'+str(n_class)+'hmm_model.pkl', 'rb'))
    models.append(model)

#log_likelihoods = pd.DataFrame()
#log_likelihoods['predicted_class'] = classes
#log_like_max = []
#top_3_loglikelihood = []
#top_3_predicted_classes = []
predicted_class = []
#is_predicted = []
true_label=[]

for i in range(len(test)):
    angle_1 = test[feature_1].iloc[i]
    angle_2 = test[feature_2].iloc[i]
    angle_3 = test[feature_3].iloc[i]
    X=np.array([angle_1,angle_2,angle_3]).T
    true_label.append(test['label'].iloc[i])
    list_log_likelihoods = []
    for model in models:
        
        list_log_likelihoods.append(model.score(X,lengths=len(X)))
        pass

    predicted_class.append(np.argmax(list_log_likelihoods))
    

In [38]:
print(predicted_class)
print(true_label)

print(len(predicted_class))
print(len(true_label))

[3, 3, 3, 5, 3, 8, 3, 2, 5, 8, 5, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 8, 3, 3, 2, 5, 3, 5, 3, 8, 5, 3, 3, 3, 5, 3, 3, 1, 3, 3, 3, 5, 3, 3, 5, 8, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 8, 8, 8, 3, 3, 3, 3, 2, 3, 2, 2, 3, 3, 8, 8, 3, 3, 5, 3, 3, 3, 3, 2, 3, 3, 3, 1, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 8, 2, 5, 5, 3, 3, 5, 5, 8, 3, 3, 2, 3, 8, 3, 2, 5, 3, 3, 3, 2, 2, 5, 3, 3, 8, 3, 3, 8, 2, 8, 3, 8, 8, 8, 2, 2, 3, 5, 8, 3, 3, 3, 3, 3, 8, 5, 3, 3, 3, 3, 5, 3, 3, 3, 1, 3, 1, 2, 3, 3, 3, 8, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 8, 3, 8, 3]
[1, 8, 2, 6, 6, 5, 1, 8, 6, 9, 8, 1, 2, 2, 0, 9, 0, 3, 9, 1, 5, 7, 6, 0, 8, 5, 3, 7, 3, 9, 3, 6, 3, 8, 3, 8, 8, 9, 0, 1, 6, 8, 6, 6, 5, 7, 3, 2, 8, 3, 2, 3, 8, 2, 2, 2, 6, 7, 7, 9, 5, 6, 8, 6, 3, 6, 7, 7, 0, 3, 9, 0, 0, 2, 0, 2, 3, 1, 1, 5, 3, 6, 0, 8, 8, 7, 9, 2, 9, 5, 9, 8, 1, 2, 0, 6, 7, 7, 9, 8, 7, 8, 8, 0, 9, 0, 3, 0, 2, 9, 6, 3, 6, 2, 5, 2, 7, 0, 9, 2, 3, 9, 6, 1, 7, 0, 7, 1, 9, 7, 7, 9, 9, 0, 5, 7, 3, 2, 3, 2, 2, 9, 6, 2, 6, 2, 0, 2, 1, 2, 3, 9, 0, 7, 9, 0, 0, 0,

In [39]:
matrix=contingency_matrix(true_label, predicted_class)
print(matrix)

[[ 0  4 14  2  1]
 [ 0  0 12  0  0]
 [ 0  0 24  2  0]
 [ 0  2 19  2  0]
 [ 0  1  4  3  1]
 [ 0  1 17  4  0]
 [ 1  5  1  1 11]
 [ 1  4 10  4  0]
 [ 2  7  2  2 11]]


In [40]:

accuracy=np.sum(np.diag(matrix))/np.sum(matrix)
print("Accuracy: ", accuracy)

Accuracy:  0.15428571428571428
